# Generated by Django 4.1 on 2024-04-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("title", models.CharField(max_length=50)),
                ("rating", models.IntegerField()),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
